# -*- coding: utf-8 -*-
"""nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NUgg6jTfjB9nyV5EAPp9bQEBbe5CK2Zz
"""

import pandas as pd

# Load the dataset
df = pd.read_csv("text_data.csv")

df.head()

df.info()

# Check for missing values in the dataset
df.isnull().sum()

df.columns

# Drop rows where 'tweet' column is missing
df.dropna(subset=['tweet'], inplace=True)

# Reset index after dropping rows
df.reset_index(drop=True, inplace=True)

df.isnull().sum()

"""preprocessing

"""

import nltk
import string
from nltk.corpus import stopwords

# Download stopwords if not already downloaded
nltk.download('stopwords')

# Define stopwords
stop_words = set(stopwords.words('english'))

# Preprocessing function to clean text
def preprocess_text(text):
    # Convert text to lowercase
    text = text.lower()
    # Remove punctuation and numbers
    text = ''.join([char for char in text if char not in string.punctuation and not char.isdigit()])
    # Tokenize and remove stopwords
    tokens = text.split()
    tokens = [word for word in tokens if word not in stop_words]
    return ' '.join(tokens)

# Apply preprocessing function to the 'tweet' column
df['clean_tweet'] = df['tweet'].apply(preprocess_text)

# Check the cleaned text
df[['tweet', 'clean_tweet']].head()

df[['tweet', 'clean_tweet']].tail()

"""**Vectorize the Text Data Using TF-IDF**

Term Frequency-Inverse Document Frequency

creating sparse matrix, where each row represents a tweet, and each column represents a unique word (feature). The values are the TF-IDF scores for each word in each document (tweet)
"""

from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize the TF-IDF Vectorizer (using top 1000 features)
vectorizer = TfidfVectorizer(max_features=1000)

# Fit and transform the cleaned text data
X = vectorizer.fit_transform(df['clean_tweet'])

# Check the shape of the resulting matrix (rows x columns)
X.shape

"""**Determine Optimal Number of Clusters (Elbow Method)**"""

import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

"""Computing K-Means for a range of k values (2 to 10 clusters)"""

inertia = []
k_values = range(2, 11)

for k in k_values:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X)
    inertia.append(kmeans.inertia_)  # Sum of squared distances

# Plot the Elbow Method
plt.figure(figsize=(10, 6))
plt.plot(k_values, inertia, marker='o', linestyle='--')
plt.title('Elbow Method for Optimal k')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia')
plt.grid(True)
plt.show()

"""**Apply K-Means Clustering**"""

# Apply K-Means clustering with the optimal number of clusters (let's say k=5)
k = 10
kmeans = KMeans(n_clusters=k, random_state=42)

# Fit the model and predict cluster labels
df['cluster'] = kmeans.fit_predict(X)

df[['tweet', 'cluster']].head()

df[['tweet', 'cluster']].tail()

"""Evaluate Clustering Quality (Silhouette Score)

computing the Silhouette Score to chaeck and  evaluate how well our clustering worked. The score ranges from -1 (bad clustering) to +1 (good clustering). A score close to 0 indicates overlapping clusters
"""

from sklearn.metrics import silhouette_score

# Calculate Silhouette Score
score = silhouette_score(X, df['cluster'])
print(f'Silhouette Score: {score}')

"""Visualize the Clusters (PCA)"""

from sklearn.decomposition import PCA

pca = PCA(n_components=2, random_state=42)
pca_result = pca.fit_transform(X.toarray())

# Plot the PCA result, coloring by cluster labels
plt.figure(figsize=(10, 6))
plt.scatter(pca_result[:, 0], pca_result[:, 1], c=df['cluster'], cmap='viridis')
plt.title('PCA Visualization of Clusters')
plt.colorbar(label='Cluster')
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.show()

"""** Incorporating Topic Modeling (LDA)**
Topic modeling with LDA can help identify common themes within the tweets and clusters. This approach assigns a probability distribution over topics for each document (tweet).
"""

from sklearn.decomposition import LatentDirichletAllocation

"""**Initializing and fiting the LDA model on the TF-IDF features**"""

lda = LatentDirichletAllocation(n_components=k, random_state=42)
lda.fit(X)

"""Displaying the top words for each topic"""

def display_lda_topics(model, feature_names, n_words=10):
    for topic_idx, topic in enumerate(model.components_):
        print(f"Topic #{topic_idx + 1}:")
        print(" ".join([feature_names[i] for i in topic.argsort()[:-n_words - 1:-1]]))
        print()

"""Getting the feature names (words) from TF-IDF"""

feature_names = vectorizer.get_feature_names_out()

display_lda_topics(lda, feature_names)

"""Visualizing Cluster Centers

Getting the cluster centers (centroids) of K-Means in the reduced 2D space
"""

centroids = pca.transform(kmeans.cluster_centers_)

"""showing the clusters with the centroids marked by red "x" symbols."""

# Plot the PCA result with cluster centers
plt.figure(figsize=(10, 6))
plt.scatter(pca_result[:, 0], pca_result[:, 1], c=df['cluster'], cmap='viridis', label='Tweets')
plt.scatter(centroids[:, 0], centroids[:, 1], c='red', marker='x', s=200, label='Cluster Centers')
plt.title('PCA Visualization of Clusters with Centroids')
plt.colorbar(label='Cluster')
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.legend()
plt.show()

"""**Interpreting Clusters (Top Terms per Cluster)**"""

import numpy as np

"""Getting the top words for each cluster based on TF-IDF scores"""

def get_top_terms_per_cluster(model, feature_names, n_top_words=10):
    top_terms = {}
    for i in range(k):
        cluster_center = model.cluster_centers_[i]
        top_indices = cluster_center.argsort()[-n_top_words:][::-1]
        top_terms[i] = [feature_names[j] for j in top_indices]
    return top_terms

"""top 10 terms for each cluster"""

top_terms = get_top_terms_per_cluster(kmeans, feature_names)

"""interpreting what each cluster is all about"""

for cluster, terms in top_terms.items():
    print(f"Cluster {cluster + 1}: {', '.join(terms)}")
